name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'
  
jobs:
  build:
    # choose the VM in which we want to run the test in
    runs-on: ubuntu-latest
    steps:
      # take all the code out of our project
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
